version: '3.8'

services:
  java_app:
    container_name: java_app
    build:
      context: .
      dockerfile: Dockerfile
    image: grifo-java-app:1.0.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/grifodb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: grifo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: grifodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
